### ISSUE TITLE
NLog target not working

### ISSUE THREAD

**Issue by escobar5** [stackify/stackify-api-dotnet#27]
I'm trying the nlog target in a new application, I've tried the troubleshooting guide with no solution. NLog is working fine, if I put I file logger, but the moment I put the stackify target `<target name="stackify" type="StackifyTarget" globalContextKeys=""
            mappedContextKeys="" callContextKeys="" logMethodNames="true" />` it stops working, even if I don't put it in `<rules>`.

Also, my Stackify configuration is ok, I've tried to log with the Direct Api and it worked.

**Comment by sporty81** [comment]
Try turning on the nlog internal logging. It is possible that you need a binding redirect due to mismatch versions of nlog.

https://stackify.com/nlog-guide-dotnet-logging/

**Comment by escobar5** [comment]
Thank you @sporty81 that was exactly the problem, it was trying to load nlog version 5.0.0, and it should be 4.0.0, a binding redirect fixed the problem.

**Comment by sporty81** [comment]
So we were just discussing this issue in the office and can't figure it out. What kind of app is your app and what target .NET framework are you using? For example, is an ASP.NET web app targeting .NET 4.6 ?

Because of .NET core and how our package is put together, you should be getting the net45 dependencies which is NLog v4, we only use v5 in the NetStandard1.3 version.

We are trying to figure out what is going on here and appreciate your help.

**Comment by escobar5** [comment]
It's a .NET 4.5.2 Owin app. I have StackifyLib v1.25.4, NLog.Targets.Stackify v1.25.4 and NLog v4.4.3
