### ISSUE TITLE
Direct api does not log according to the default example

### ISSUE THREAD

**Issue by thomaseyde** [stackify/stackify-api-dotnet#3]
I am testing the direct api with NUnit tests and the test project's app.config contains the three required `appSettings` keys, but nothing is logged.

I installed the nuget package.

There are a few calls on `Logger` which should read the api key, but that doesn't happen. The internal HttpClient should even read the api key when it's not given, but doesn't.

The only way I have gotten the direct api to actually log, is to manually set the `ApiKey` and call `Shutdown()` at the end. I haven't seen any references to `Shutdown()` btw,

Here are the things I have tried:

    [TestFixture]
    public class Log_to_stackify
    {
        [Test]
        public void Api_key_is_not_read_from_config()
        {
            Logger.ApiKey.ShouldNotBeNull();
        }

        [Test]
        public void Api_key_should_have_been_read_but_its_not()
        {
            Logger.CanSend();
            Logger.ApiKey.ShouldNotBeNull();
        }

        [Test]
        public void The_default_example_does_not_log_anything()
        {
            Logger.QueueException(new ApplicationException("Sky is falling"));
        }

        [Test]
        public void Must_set_api_key_manually_and_call_shutdown_in_order_to_log()
        {
            Logger.ApiKey = ConfigurationManager.AppSettings["Stackify.ApiKey"];
            Logger.QueueException(new ApplicationException("Sky is falling"));
            Logger.Shutdown();
        }
    }

**Comment by sporty81** [comment]
Thanks for your feedback.

The library is optimized for asynchronous usage and background processing. Since the library is designed to be asynchronous, Shutdown() does have to be called to force everything to be flushed. LogClient is really the key class and calling shutdown forces it to flush the queue.

With log4net, as an example, we automatically catch the OnClose method and do the proper flushing. But if you are using the API directly we don't have any sort of automatically flushing built in without manually calling Shutdown.

I'll update the example readme to include a note about this.

We don't really recommend using our Logger class directly for logging, but that does not mean you can't! We would suggest using NLog or log4net so you have more flexibility for logging to text files and such as well.

Logger.ApiKey is meant as a way to override the config and really serves no purpose as a "get". I'll check in to why it doesn't work though.

**Comment by sporty81** [comment]
Logger.ApiKey should now work properly when doing a "get" on it. 

https://github.com/stackify/stackify-api-dotnet/commit/65396a4db29426e06b934a3607df6d0916dd023b

**Comment by thomaseyde** [comment]
Can you update the NuGet package as well?
