### ISSUE TITLE
Require Log4Net 1.2.14 (2.0.4) or better

### ISSUE THREAD

**Issue by AdamCLarsen** [stackify/stackify-api-dotnet#7]
See pull request #6.

Log4Net 1.2.14 (2.0.4) added LogicalThreadContextStack, see https://issues.apache.org/jira/browse/LOG4NET-455

Knowing there is an issue with Log4Net prior to version 2.0.4 with a feature that is directly supported, and as Async/Await is more commonly used, it would be good to ensure we don't have this bug as well.

Once 2.0.4 is the minimum version required, we can remove the use of a string compare for type check in the Log4Net Appender.

**Comment by sporty81** [comment]
The problem we have is we hate to force our nuget package to require 2.0.4 and force people to upgrade. This has long been a problem with all these log appenders. Everyone uses all sorts of versions (include the ancient log4net versions!) and the assembly references are always sort of a pain because they are strongly typed.

**Comment by AdamCLarsen** [comment]
Absolutely, agree.  When looking at the pros for upgrading (performance, stability, supportability), they are all negligible when compared to compatibility.  I only bring up the issue to make sure it has visibility, but is something that I would put on a backlog, and revisited next year.
